### ISSUE TITLE
golang: Install binaries via vim

### ISSUE THREAD

**Issue by belminf** [belminf/ansible-playbooks#3]
`vim +GoInstallBinaries +qall`

Right now, doing the following just locks up:

```
-  name: install go binaries
   command: vim +GoInstallBinaries +qall
   environment:
     GOPATH: ~/go
   args:
     creates: ~/go/bin
```
